# Generated by Django 2.2.1 on 2019-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='videoName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
