# Generated by Django 2.2.1 on 2019-08-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitmeapp', '0002_thumbnail_videoname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='cateDetailName',
            new_name='firstCate',
        ),
        migrations.RenameField(
            model_name='thumbnail',
            old_name='cateName',
            new_name='secondCate',
        ),
        migrations.RenameField(
            model_name='thumbnail',
            old_name='majorTitle',
            new_name='thirdCate',
        ),
        migrations.RenameField(
            model_name='thumbnail',
            old_name='subTitle',
            new_name='title',
        ),
    ]
