# Generated by Django 2.2.1 on 2019-08-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitmeapp', '0003_auto_20190809_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Secondcate', models.CharField(max_length=20, unique=True)),
                ('CateNum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitmeapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='T_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Thirdcate', models.CharField(max_length=20, unique=True)),
                ('S_CateNum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitmeapp.S_category')),
            ],
        ),
    ]
