# Generated by Django 2.2.1 on 2019-08-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitmeapp', '0005_infovideo_likevideo_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='cate_number',
            new_name='f_cate_number',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='s_cate_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitmeapp.S_category'),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='t_cate_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitmeapp.T_category'),
        ),
    ]
