# Generated by Django 2.2.1 on 2019-08-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitmeapp', '0007_likevideo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='infovideo',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
